# Generated by Django 4.2.6 on 2023-10-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('doe', models.DateField()),
                ('num_copies', models.IntegerField()),
            ],
        ),
    ]
